// Trip status constants
export const TRIP_STATUS = {
  PLANNING: 'planning',
  ACTIVE: 'active',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

// Trip status display names
export const TRIP_STATUS_LABELS = {
  [TRIP_STATUS.PLANNING]: 'Planning',
  [TRIP_STATUS.ACTIVE]: 'Active',
  [TRIP_STATUS.COMPLETED]: 'Completed',
  [TRIP_STATUS.CANCELLED]: 'Cancelled'
};

// Trip status colors (for UI)
export const TRIP_STATUS_COLORS = {
  [TRIP_STATUS.PLANNING]: '#FFA500', // Orange
  [TRIP_STATUS.ACTIVE]: '#4CAF50',   // Green
  [TRIP_STATUS.COMPLETED]: '#2196F3', // Blue
  [TRIP_STATUS.CANCELLED]: '#F44336'  // Red
};

// Trip data model structure
export const TRIP_MODEL = {
  id: '',              // Auto-generated by Firestore
  userId: '',          // User ID (for access control)
  name: '',            // Trip name/title
  location: '',        // Destination
  startDate: null,     // Start date (Date object)
  endDate: null,       // End date (Date object)
  description: '',     // Optional trip notes
  status: TRIP_STATUS.PLANNING, // Trip status
  createdAt: null,     // Creation timestamp
  updatedAt: null      // Last update timestamp
};

// Validation rules
export const TRIP_VALIDATION = {
  name: {
    required: true,
    minLength: 1,
    maxLength: 100
  },
  location: {
    required: true,
    minLength: 1,
    maxLength: 100
  },
  startDate: {
    required: true
  },
  endDate: {
    required: true
  },
  description: {
    required: false,
    maxLength: 500
  }
};

// Default trip values
export const DEFAULT_TRIP = {
  name: '',
  location: '',
  startDate: new Date(),
  endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
  description: '',
  status: TRIP_STATUS.PLANNING
};
